app: Apache
org: B
environment: prod
service: Infrastructure
data_classification: private
account_id: "044254960108"
account_name: Sandbox
region: ap-southeast-2
production_data: false
vpc_id: vpc-xxxxxxxxxxxxxxxxx
instance_type: "t3.medium"